server:
  port: 8083

spring:
  jpa:    database-platform: org.hibernate.dialect.Oracle10gDialect    datasource:
    url: jdbc:oracle:thin:@localhost:1522/xe
    username: QA_DB
    password: learning
    driver-class-name: oracle.jdbc.driver.OracleDriver
    